### ISSUE TITLE
Error when opening in browser

### ISSUE THREAD

**Issue by rockneurotiko** [woshilaiceshide/scala-web-repl#2]
Hi! 

Awesome project :smile: 

I downloaded `s-server` and made the `publishLocal`, then I downloaded this and executed `sbt run`.

This executes the `DefaultBootsrap` and seems ok, but, when I enter the address in the browser (`http://0.0.0.0:8181/asset/wrepl.html`) this trace appears and the server breaks.

```
[info] Running woshilaiceshide.wrepl.DefaultBootstrap 
[error] (wrepl-worker) scala.reflect.internal.FatalError: class StringContext does not have a member f
scala.reflect.internal.FatalError: class StringContext does not have a member f
    at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1186)
    at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1203)
    at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1238)
    at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f$lzycompute(Definitions.scala:1424)
    at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f(Definitions.scala:1424)
    at scala.tools.reflect.FastTrack$$anonfun$1.apply(FastTrack.scala:54)
    at scala.tools.reflect.FastTrack$$anonfun$1.apply(FastTrack.scala:46)
    at scala.reflect.internal.SymbolTable$perRunCaches$$anonfun$newGeneric$1.apply(SymbolTable.scala:387)
    at scala.tools.reflect.FastTrack.contains(FastTrack.scala:21)
    at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1195)
    at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1530)
    at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1542)
    at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:782)
    at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:781)
    at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:781)
    at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1569)
    at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:781)
    at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:773)
    at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1685)
    at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1693)
    at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1683)
    at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1489)
    at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1634)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5007)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5395)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5422)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5369)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5373)
    at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
    at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5451)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3047)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
    at scala.collection.immutable.List.loop$1(List.scala:173)
    at scala.collection.immutable.List.mapConserve(List.scala:189)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3151)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1921)
    at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1762)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5308)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5358)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5395)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5422)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5369)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5373)
    at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
    at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5451)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3047)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
    at scala.collection.immutable.List.loop$1(List.scala:173)
    at scala.collection.immutable.List.mapConserve(List.scala:189)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3151)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5014)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5311)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5358)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5395)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5422)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5369)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5373)
    at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5447)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
    at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
    at scala.tools.nsc.interpreter.IMain.scala$tools$nsc$interpreter$IMain$$_initialize(IMain.scala:132)
    at scala.tools.nsc.interpreter.IMain.initializeSynchronous(IMain.scala:153)
    at woshilaiceshide.wrepl.repl.PipedRepl$$anon$1$$anonfun$process$1.apply$mcZ$sp(PipedRepl.scala:112)
    at woshilaiceshide.wrepl.repl.PipedRepl$$anon$1$$anonfun$process$1.apply(PipedRepl.scala:103)
    at woshilaiceshide.wrepl.repl.PipedRepl$$anon$1$$anonfun$process$1.apply(PipedRepl.scala:103)
    at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
    at woshilaiceshide.wrepl.repl.PipedRepl$$anon$1.process(PipedRepl.scala:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at woshilaiceshide.wrepl.repl.PipedRepl$$anon$2.run(PipedRepl.scala:225)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by woshilaiceshide** [comment]
Thanks for your comment.
I found that Scala-Web-REPL can not run in the same jvm as sbt. It should be forked into another jvm. Write 'fork := true' in build.sbt or issue 'set fork := true' in sbt's console.

I've updated the build.sbt and README.md.

I'll write a java agent that will make easier when adding Scala-Web-REPL in users' own application.

The entire project has been updated and refined today, maybe you can try the newest one.

Thanks.
